/**
 * track_usage Tool
 *
 * Records an AI Resource invocation for telemetry purposes.
 *
 * This tool is automatically invoked by the AI at the start of every
 * Command or Skill execution.  The Prompt content generated by
 * PromptGenerator prepends a system instruction that asks the AI to
 * call `track_usage` before doing anything else, so that the server
 * can record the usage even though Cursor does not call `prompts/get`
 * when a slash command is selected.
 *
 * The tool is intentionally lightweight:
 *   - No external API calls.
 *   - Fire-and-forget write to the local telemetry file.
 *   - Always returns a success response so the AI continues normally.
 */

import { logger } from '../utils/logger';
import { telemetry } from '../telemetry/index.js';
import type { ToolResult } from '../types/tools';

export interface TrackUsageParams {
  resource_id: string;
  resource_type: 'command' | 'skill';
  resource_name: string;
  /** Automatically injected by the MCP server from the SSE token. */
  user_token?: string;
  /** Optional Jira Issue ID for usage correlation (e.g. "PROJ-12345"). */
  jira_id?: string;
}

export async function trackUsage(params: unknown): Promise<ToolResult<{ recorded: boolean }>> {
  const p = params as TrackUsageParams;

  const resourceId   = p.resource_id   ?? '';
  const resourceType = p.resource_type ?? 'command';
  const resourceName = p.resource_name ?? '';
  const userToken    = p.user_token    ?? '';
  const jiraId       = typeof p.jira_id === 'string' && p.jira_id.trim() !== ''
    ? p.jira_id.trim()
    : undefined;

  if (!resourceId || !userToken) {
    // Missing required fields — log and return without recording so the AI
    // is not blocked.  This should not happen in normal operation.
    logger.warn(
      { resourceId, userToken: !!userToken },
      'track_usage called with missing resource_id or user_token — skipping',
    );
    return { success: true, data: { recorded: false } };
  }

  // Await the write to ensure the event is persisted before the periodic flush
  // timer fires and clears pending_events.  File write latency is negligible
  // (< 1 ms) so this does not meaningfully delay the tool response.
  await telemetry
    .recordInvocation(resourceId, resourceType, resourceName, userToken, jiraId)
    .catch((err) => {
      logger.warn({ resourceId, error: (err as Error).message }, 'track_usage: telemetry write failed (non-critical)');
    });

  logger.info(
    { resourceId, resourceType, resourceName, jiraId: jiraId ?? '(none)' },
    'track_usage: invocation recorded',
  );

  return { success: true, data: { recorded: true } };
}

export const trackUsageTool = {
  name: 'track_usage',
  description:
    'Record the invocation of an AI Resource (Command or Skill) for telemetry. ' +
    'MUST be called at the very beginning of every Command or Skill execution, ' +
    'before performing any other action. ' +
    'The resource_id, resource_type, and resource_name are provided in the prompt header — ' +
    'copy them exactly as given. ' +
    'user_token is injected automatically by the server; do NOT ask the user for it. ' +
    'jira_id is optional — only include it if the user explicitly mentions a Jira issue number.',
  inputSchema: {
    type: 'object' as const,
    properties: {
      resource_id: {
        type: 'string',
        description: 'Canonical resource ID as shown in the prompt header (e.g. "cmd-client-sdk-ai-hub-generate-testcase").',
      },
      resource_type: {
        type: 'string',
        enum: ['command', 'skill'],
        description: 'Resource type: "command" or "skill".',
      },
      resource_name: {
        type: 'string',
        description: 'Human-readable resource name as shown in the prompt header (e.g. "generate-testcase").',
      },
      user_token: {
        type: 'string',
        description:
          'DO NOT set this field — it is automatically injected by the MCP server from ' +
          'the authenticated SSE connection.',
      },
      jira_id: {
        type: 'string',
        description:
          'Optional Jira Issue ID for usage correlation (e.g. "PROJ-12345"). ' +
          'Only include if the user explicitly mentioned a Jira issue in this conversation.',
      },
    },
    required: ['resource_id', 'resource_type', 'resource_name'],
  },
  handler: trackUsage,
};
