/**
 * Codex Policy Generator
 *
 * Aggregates all subscribed CSP routing rule contents into a single
 * `csp-routing-policy.md` markdown file that is injected into Codex via
 * the `developer_instructions` key in `~/.codex/config.toml`.
 *
 * Design rationale:
 * - Codex does not support per-file `.mdc` rule directories like Cursor does.
 * - The `developer_instructions` config key accepts a freeform string that
 *   Codex loads at session startup as additional system instructions.
 * - Rather than dumping raw rule content into config.toml (size / escaping
 *   issues), we write a stable policy file path and instruct Codex to read it.
 * - The policy file itself is a well-structured markdown document that Codex
 *   can parse and apply during the session.
 */

export interface RuleContent {
  name: string;
  content: string;
}

/**
 * Generates the aggregated `csp-routing-policy.md` content from the given
 * list of rule contents.
 *
 * The output format is a self-describing markdown document with:
 * - A header section explaining the file purpose.
 * - One `##` section per rule, using the rule name as the heading.
 * - A generation timestamp for cache-busting diagnostics.
 */
export function generatePolicyContent(rules: RuleContent[]): string {
  const timestamp = new Date().toISOString();

  const ruleSections = rules
    .map(({ name, content }) => {
      const sanitisedName = name.replace(/[`*#]/g, ' ').trim();
      return `## ${sanitisedName}\n\n${content.trim()}`;
    })
    .join('\n\n---\n\n');

  return [
    '---',
    'title: CSP AI Agent Routing Policy',
    `generated_at: ${timestamp}`,
    `rule_count: ${rules.length}`,
    '---',
    '',
    '# CSP AI Agent Routing Policy',
    '',
    '> Auto-generated by CSP AI Agent MCP. Do not edit manually.',
    '> This file is refreshed automatically on `sync_resources`.',
    '',
    ruleSections,
    '',
  ].join('\n');
}
